// <auto-generated />
namespace Phobos.Library.CoreServices.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserRole_Functionality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRole_Functionality));
        
        string IMigrationMetadata.Id
        {
            get { return "201605271443390_UserRole_Functionality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
